# Generated by Django 5.1.1 on 2024-10-04 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_jurnal_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jurnal',
            options={'ordering': ('position', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('position', 'difficulty', '-created_at'), 'verbose_name_plural': 'tasks'},
        ),
    ]
